export default [
  {
    name: 'Michael Schmitt',
    post: 'Founder & CEO',
    color: 'red',
    image: '',
    title: '#1 About Bennet.',
    text: "Monetization first mover advantage iPad. Interaction design buzz handshake. Stealth agile development branding. Backing facebook hackathon conversion startup scrum project niche market business-to-consumer paradigm shift traction. Rockstar bandwidth twitter ownership success disruptive series A financing user experience buyer client social proof validation hypotheses. User experience crowdfunding facebook seed round A/B testing mass market.",
    linkFB: 'https://facebook.com/',
    linkTwitter: 'https://twitter.com',
    linkLinkedIn: 'https://www.linkedin.com/',
    linkInstagram: 'https://www.instagram.com',
  },
  {
    name: 'David Krämer',
    post: 'Lead Developer',
    color: 'green',
    image: '',
    title: '#2 About Bennet.',
    text: "Monetization first mover advantage iPad. Interaction design buzz handshake. Stealth agile development branding. Backing facebook hackathon conversion startup scrum project niche market business-to-consumer paradigm shift traction. Rockstar bandwidth twitter ownership success disruptive series A financing user experience buyer client social proof validation hypotheses. User experience crowdfunding facebook seed round A/B testing mass market.",
    linkFB: 'https://facebook.com/',
    linkTwitter: 'https://twitter.com',
    linkLinkedIn: 'https://www.linkedin.com/',
    linkInstagram: 'https://www.instagram.com',
  },
  {
    name: 'Anna Schröder',
    post: 'Designer',
    color: 'purpure',
    image: '',
    title: '#3 About Bennet.',
    text: "Monetization first mover advantage iPad. Interaction design buzz handshake. Stealth agile development branding. Backing facebook hackathon conversion startup scrum project niche market business-to-consumer paradigm shift traction. Rockstar bandwidth twitter ownership success disruptive series A financing user experience buyer client social proof validation hypotheses. User experience crowdfunding facebook seed round A/B testing mass market.",
    linkFB: 'https://facebook.com/',
    linkTwitter: 'https://twitter.com',
    linkLinkedIn: 'https://www.linkedin.com/',
    linkInstagram: 'https://www.instagram.com',
  },
  {
    name: 'Jason Teichmann',
    post: 'Consultant',
    color: 'yellow',
    image: '',
    title: '#4 About Bennet.',
    text: "Monetization first mover advantage iPad. Interaction design buzz handshake. Stealth agile development branding. Backing facebook hackathon conversion startup scrum project niche market business-to-consumer paradigm shift traction. Rockstar bandwidth twitter ownership success disruptive series A financing user experience buyer client social proof validation hypotheses. User experience crowdfunding facebook seed round A/B testing mass market.",
    linkFB: 'https://facebook.com/',
    linkTwitter: 'https://twitter.com',
    linkLinkedIn: 'https://www.linkedin.com/',
    linkInstagram: 'https://www.instagram.com',
  }
]